project:
  type: website
  output-dir: docs

website:
  title: "My Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css



