project:
  type: website
  output-dir: docs

website:
  title: "Stefan's AI Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/stefan-jo
      - icon: linkedin
        href: https://www.linkedin.com/in/stefan-josef-7a5a6b120
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css



